#lang racket/base
;; Property-based tests using redex-check
;;
;; Verifies algebraic properties that should hold for all values
;; generated by the random term generator.

(require redex/reduction-semantics
         rackunit
         "../lang/core.rkt"
         "../lang/preprocessing.rkt"
         "../semantics/truthiness.rkt"
         "../semantics/env.rkt"
         "../semantics/merge.rkt"
         "../semantics/eval.rkt")

(provide property-tests)

;; Number of attempts for each redex-check property
(define ATTEMPTS 200)

;; Helper: evaluate and return single result, or #f if no/multiple results
(define (eval-single e σ)
  (define results (judgment-holds (eval ,e ,σ v) v))
  (and (= (length results) 1)
       (car results)))


(define property-tests
  (test-suite
   "Property-based tests"

   ;; ── Values self-evaluate ──────────────────────────────────────
   ;; Any value v in any (possibly empty) environment evaluates to itself.

   (test-case "values self-evaluate (empty env)"
     (redex-check
      Iidy-Core v
      (let ([result (eval-single (term v) (term ()))])
        (and result (equal? result (term v))))
      #:attempts ATTEMPTS))

   ;; ── Escape is identity on values ──────────────────────────────

   (test-case "escape is identity on values"
     (redex-check
      Iidy-Core v
      (let ([result (eval-single (term (escape v)) (term ()))])
        (and result (equal? result (term v))))
      #:attempts ATTEMPTS))

   ;; ── Eq is reflexive ──────────────────────────────────────────

   (test-case "eq is reflexive"
     (redex-check
      Iidy-Core v
      (let ([result (eval-single (term (eq v v)) (term ()))])
        (and result (equal? result (term (bool #t)))))
      #:attempts ATTEMPTS))

   ;; ── Not is involutory on booleans ─────────────────────────────
   ;; not(not(v)) should have the same truthiness as v

   (test-case "double negation preserves truthiness"
     (redex-check
      Iidy-Core v
      (let ([single (eval-single (term (not (not v))) (term ()))]
            [truth (term (truthy v))])
        (and single
             (if truth
                 (equal? single (term (bool #t)))
                 (equal? single (term (bool #f))))))
      #:attempts ATTEMPTS))

   ;; ── Merge with empty is identity ──────────────────────────────

   (test-case "merge obj with empty obj (left identity)"
     (redex-check
      Iidy-Core (obj ((k v) ...))
      (let ([result (eval-single (term (merge ((obj ()) (obj ((k v) ...))))) (term ()))])
        (and result (equal? result (term (obj ((k v) ...))))))
      #:attempts ATTEMPTS))

   (test-case "merge obj with empty obj (right identity)"
     (redex-check
      Iidy-Core (obj ((k v) ...))
      (let ([result (eval-single (term (merge ((obj ((k v) ...)) (obj ())))) (term ()))])
        (and result (equal? result (term (obj ((k v) ...))))))
      #:attempts ATTEMPTS))

   ;; ── Concat with empty is identity ─────────────────────────────

   (test-case "concat arr with empty arr (left identity)"
     (redex-check
      Iidy-Core (arr (v ...))
      (let ([result (eval-single (term (concat ((arr ()) (arr (v ...))))) (term ()))])
        (and result (equal? result (term (arr (v ...))))))
      #:attempts ATTEMPTS))

   (test-case "concat arr with empty arr (right identity)"
     (redex-check
      Iidy-Core (arr (v ...))
      (let ([result (eval-single (term (concat ((arr (v ...)) (arr ())))) (term ()))])
        (and result (equal? result (term (arr (v ...))))))
      #:attempts ATTEMPTS))

   ;; ── Lookup after extend finds the value ───────────────────────

   (test-case "lookup finds extended binding"
     (redex-check
      Iidy-Core v
      (let ([env (term (extend "test-key" v ()))])
        (equal? (term (lookup "test-key" ,env)) (term v)))
      #:attempts ATTEMPTS))

   ;; ── val->text produces a string ──────────────────────────────

   (test-case "val->text always produces a string"
     (redex-check
      Iidy-Core v
      (string? (term (val->text v)))
      #:attempts ATTEMPTS))

   ;; ── Truthy is total (always returns #t or #f) ────────────────

   (test-case "truthy is total"
     (redex-check
      Iidy-Core v
      (boolean? (term (truthy v)))
      #:attempts ATTEMPTS))

   (test-case "truthy/hbs is total"
     (redex-check
      Iidy-Core v
      (boolean? (term (truthy/hbs v)))
      #:attempts ATTEMPTS))

   (test-case "truthy/jmespath is total"
     (redex-check
      Iidy-Core v
      (boolean? (term (truthy/jmespath v)))
      #:attempts ATTEMPTS))))
