#lang racket/base
;; Property-based tests using redex-check
;;
;; Verifies algebraic properties that should hold for all values
;; generated by the random term generator.

(require redex/reduction-semantics
         rackunit
         "../lang/core.rkt"
         "../lang/preprocessing.rkt"
         "../lang/handlebars.rkt"
         "../lang/jmespath.rkt"
         "../semantics/truthiness.rkt"
         "../semantics/env.rkt"
         "../semantics/merge.rkt"
         "../semantics/eval.rkt"
         "../semantics/handlebars-eval.rkt"
         "../semantics/jmespath-eval.rkt"
         "../semantics/bracket-expansion.rkt")

(provide property-tests)

;; Number of attempts for each redex-check property
(define ATTEMPTS 200)

;; Helper: evaluate and return single result, or #f if no/multiple results
(define (eval-single e σ)
  (define results (judgment-holds (eval ,e ,σ v) v))
  (and (= (length results) 1)
       (car results)))


(define property-tests
  (test-suite
   "Property-based tests"

   ;; ── Values self-evaluate ──────────────────────────────────────
   ;; Any value v in any (possibly empty) environment evaluates to itself.

   (test-case "values self-evaluate (empty env)"
     (redex-check
      Iidy-Core v
      (let ([result (eval-single (term v) (term ()))])
        (and result (equal? result (term v))))
      #:attempts ATTEMPTS))

   ;; ── Escape is identity on values ──────────────────────────────

   (test-case "escape is identity on values"
     (redex-check
      Iidy-Core v
      (let ([result (eval-single (term (escape v)) (term ()))])
        (and result (equal? result (term v))))
      #:attempts ATTEMPTS))

   ;; ── Eq is reflexive ──────────────────────────────────────────

   (test-case "eq is reflexive"
     (redex-check
      Iidy-Core v
      (let ([result (eval-single (term (eq v v)) (term ()))])
        (and result (equal? result (term (bool #t)))))
      #:attempts ATTEMPTS))

   ;; ── Not is involutory on booleans ─────────────────────────────
   ;; not(not(v)) should have the same truthiness as v

   (test-case "double negation preserves truthiness"
     (redex-check
      Iidy-Core v
      (let ([single (eval-single (term (not (not v))) (term ()))]
            [truth (term (truthy v))])
        (and single
             (if truth
                 (equal? single (term (bool #t)))
                 (equal? single (term (bool #f))))))
      #:attempts ATTEMPTS))

   ;; ── Merge with empty is identity ──────────────────────────────

   (test-case "merge obj with empty obj (left identity)"
     (redex-check
      Iidy-Core (obj ((k v) ...))
      (let ([result (eval-single (term (merge ((obj ()) (obj ((k v) ...))))) (term ()))])
        (and result (equal? result (term (obj ((k v) ...))))))
      #:attempts ATTEMPTS))

   (test-case "merge obj with empty obj (right identity)"
     (redex-check
      Iidy-Core (obj ((k v) ...))
      (let ([result (eval-single (term (merge ((obj ((k v) ...)) (obj ())))) (term ()))])
        (and result (equal? result (term (obj ((k v) ...))))))
      #:attempts ATTEMPTS))

   ;; ── Concat with empty is identity ─────────────────────────────

   (test-case "concat arr with empty arr (left identity)"
     (redex-check
      Iidy-Core (arr (v ...))
      (let ([result (eval-single (term (concat ((arr ()) (arr (v ...))))) (term ()))])
        (and result (equal? result (term (arr (v ...))))))
      #:attempts ATTEMPTS))

   (test-case "concat arr with empty arr (right identity)"
     (redex-check
      Iidy-Core (arr (v ...))
      (let ([result (eval-single (term (concat ((arr (v ...)) (arr ())))) (term ()))])
        (and result (equal? result (term (arr (v ...))))))
      #:attempts ATTEMPTS))

   ;; ── Lookup after extend finds the value ───────────────────────

   (test-case "lookup finds extended binding"
     (redex-check
      Iidy-Core v
      (let ([env (term (extend "test-key" v ()))])
        (equal? (term (lookup "test-key" ,env)) (term v)))
      #:attempts ATTEMPTS))

   ;; ── val->text produces a string ──────────────────────────────

   (test-case "val->text always produces a string"
     (redex-check
      Iidy-Core v
      (string? (term (val->text v)))
      #:attempts ATTEMPTS))

   ;; ── Truthy is total (always returns #t or #f) ────────────────

   (test-case "truthy is total"
     (redex-check
      Iidy-Core v
      (boolean? (term (truthy v)))
      #:attempts ATTEMPTS))

   (test-case "truthy/hbs is total"
     (redex-check
      Iidy-Core v
      (boolean? (term (truthy/hbs v)))
      #:attempts ATTEMPTS))

   (test-case "truthy/jmespath is total"
     (redex-check
      Iidy-Core v
      (boolean? (term (truthy/jmespath v)))
      #:attempts ATTEMPTS))


   ;; ── env-to-obj always produces an obj ────────────────────────

   (test-case "env-to-obj always produces an obj"
     (redex-check
      Iidy-Core σ
      (redex-match? Iidy-Core (obj ((k v) ...)) (term (env-to-obj σ)))
      #:attempts ATTEMPTS))


   ;; ── val->json always produces a string ───────────────────────

   (test-case "val->json always produces a string"
     (redex-check
      Iidy-Core v
      (string? (val->json (term v)))
      #:attempts ATTEMPTS))


   ;; ── Handlebars: hb-val->text is total ────────────────────────

   (test-case "hb-val->text is total"
     (redex-check
      Iidy-Core v
      (string? (term (hb-val->text v)))
      #:attempts ATTEMPTS))


   ;; ── Handlebars: hb-lookup returns a value ────────────────────
   ;; Looking up any path in any value always returns a value (null for miss).

   (test-case "hb-lookup is total (empty path)"
     (redex-check
      Iidy-Core v
      (redex-match? Iidy-Core v (term (hb-lookup () v)))
      #:attempts ATTEMPTS))


   ;; ── JMESPath: jeval identity is identity ─────────────────────

   (test-case "jeval identity returns input"
     (redex-check
      Iidy-Core v
      (equal? (term (jeval jidentity v)) (term v))
      #:attempts ATTEMPTS))


   ;; ── JMESPath: jeval literal ignores context ──────────────────

   (test-case "jeval literal ignores context"
     (redex-check
      Iidy-Core v
      (equal? (term (jeval (jlit v) null)) (term v))
      #:attempts ATTEMPTS))


   ;; ── JMESPath: jcompare == is reflexive ───────────────────────

   (test-case "jcompare == is reflexive"
     (redex-check
      Iidy-Core v
      (equal? (term (jcompare == v v)) (term #t))
      #:attempts ATTEMPTS))


   ;; ── Bracket expansion: literal-only paths pass through ───────

   (test-case "expand-path with no bracket-refs is identity"
     (redex-check
      Iidy-Core σ
      (let ([path (term ("a" "b" "c"))])
        (equal? (term (expand-path ,path σ)) path))
      #:attempts ATTEMPTS))


   ;; ── Serialization: to-yaml produces a string ─────────────────

   (test-case "to-yaml always produces a string result"
     (redex-check
      Iidy-Core v
      (let ([result (eval-single (term (to-yaml v)) (term ()))])
        (and result (redex-match? Iidy-Core (str s) result)))
      #:attempts ATTEMPTS))

   ;; ── Serialization: to-json produces a string ─────────────────

   (test-case "to-json always produces a string result"
     (redex-check
      Iidy-Core v
      (let ([result (eval-single (term (to-json v)) (term ()))])
        (and result (redex-match? Iidy-Core (str s) result)))
      #:attempts ATTEMPTS))))
