# A custom resource template that creates an SQS queue with CloudWatch alarms.
# Used as a synthetic resource type in CFN templates.
$params:
  - Name: QueueLabel
    Type: String
  - Name: RedrivePolicy
    Default: !Ref 'AWS::NoValue'
  - Name: AlarmPeriod
    Type: Number
    Default: 60
  - Name: AlarmEvaluationPeriods
    Type: Number
    Default: 2
  - Name: AlarmMaxQueueDepth
    Type: Number
    Default: 250
  - Name: AlarmMaxMessageAge
    Type: Number
    Default: 60
  - Name: AlarmPriority
    Type: String
    Default: "P3"

Parameters:
  Environment:
    Type: String
    $global: true
  AlertTopicArn:
    Type: String
    $global: true

Resources:
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub app--${Environment}--{{QueueLabel}}
      MessageRetentionPeriod: 1209600
      VisibilityTimeout: 30
      RedrivePolicy: !$ RedrivePolicy

  QueueDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '{{AlarmPriority}}--${Queue.QueueName}-depth'
      EvaluationPeriods: !$ AlarmEvaluationPeriods
      Dimensions:
        - Name: QueueName
          Value: !GetAtt Queue.QueueName
      AlarmActions:
        - !Ref AlertTopicArn
      AlarmDescription: 'Queue depth exceeded threshold'
      Namespace: AWS/SQS
      Period: !$ AlarmPeriod
      ComparisonOperator: GreaterThanThreshold
      Statistic: Sum
      Threshold: !$ AlarmMaxQueueDepth
      OKActions:
        - !Ref AlertTopicArn
      MetricName: ApproximateNumberOfMessagesVisible

  QueueAgeAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '{{AlarmPriority}}--${Queue.QueueName}-age'
      EvaluationPeriods: !$ AlarmEvaluationPeriods
      Dimensions:
        - Name: QueueName
          Value: !GetAtt Queue.QueueName
      AlarmActions:
        - !Ref AlertTopicArn
      AlarmDescription: 'Message age exceeded threshold'
      Namespace: AWS/SQS
      Period: !$ AlarmPeriod
      ComparisonOperator: GreaterThanThreshold
      Statistic: Maximum
      Threshold: !$ AlarmMaxMessageAge
      OKActions:
        - !Ref AlertTopicArn
      MetricName: ApproximateAgeOfOldestMessage

Outputs:
  QueueUrl:
    Value: !Ref Queue
  QueueArn:
    Value: !GetAtt Queue.Arn
