module Iidy.Aws.ClientReqToken
  ( TokenInfo(..)
  , TokenSource(..)
  , DerivedTokenInfo(..)
  ) where

import Data.Text (Text)

data DerivedTokenInfo = DerivedTokenInfo
  { dtiFrom :: !Text
  , dtiStep :: !Text
  } deriving stock (Show, Eq)

data TokenSource
  = UserProvided
  | AutoGenerated
  | Derived !DerivedTokenInfo
  deriving stock (Show, Eq)

data TokenInfo = TokenInfo
  { tiValue       :: !Text
  , tiSource      :: !TokenSource
  , tiOperationId :: !Text
  } deriving stock (Show, Eq)
