-- | Client request token management for CloudFormation idempotency.
--
-- Provides token generation and deterministic derivation for multi-step
-- operations. Derived tokens use SHA256 hashing to ensure the same inputs
-- always produce the same output, enabling safe retries.
module Iidy.Aws.ClientReqToken
  ( TokenInfo(..)
  , TokenSource(..)
  , DerivedTokenInfo(..)
  , deriveTokenForStep
  , formatTokenSource
  ) where

import Data.ByteArray (convert)
import Data.ByteArray.Encoding (Base(..), convertToBase)
import Data.ByteString (ByteString)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Text.Encoding (encodeUtf8, decodeUtf8)

import Crypto.Hash (SHA256(..), hashWith)

data DerivedTokenInfo = DerivedTokenInfo
  { dtiFrom :: !Text
  , dtiStep :: !Text
  } deriving stock (Show, Eq)

data TokenSource
  = UserProvided
  | AutoGenerated
  | Derived !DerivedTokenInfo
  deriving stock (Show, Eq)

data TokenInfo = TokenInfo
  { tiValue       :: !Text
  , tiSource      :: !TokenSource
  , tiOperationId :: !Text
  } deriving stock (Show, Eq)

-- | Derive a new token for a specific operation step.
-- Uses SHA256 hash of (primary_token + step) for deterministic derivation.
-- Format: "{primary_first_8_chars}-{hash_first_8_chars}"
deriveTokenForStep :: TokenInfo -> Text -> TokenInfo
deriveTokenForStep primary step =
  let input = encodeUtf8 (tiValue primary <> step)
      digest = hashWith SHA256 input
      hashBytes = convert digest :: ByteString
      hashHex = T.toLower $ decodeUtf8 (convertToBase Base16 hashBytes)
      prefix = T.take 8 (tiValue primary)
      suffix = T.take 8 hashHex
      derivedValue = prefix <> "-" <> suffix
  in TokenInfo
    { tiValue = derivedValue
    , tiSource = Derived DerivedTokenInfo
        { dtiFrom = tiValue primary
        , dtiStep = step
        }
    , tiOperationId = tiOperationId primary
    }

-- | Format a token source for display
formatTokenSource :: TokenSource -> Text
formatTokenSource = \case
  UserProvided       -> "user-provided"
  AutoGenerated      -> "auto-generated"
  Derived dti        -> "derived from " <> dtiFrom dti <> " at " <> dtiStep dti
