{- | Client request token management for CloudFormation idempotency.

Provides token generation and deterministic derivation for multi-step
operations. Derived tokens use SHA256 hashing to ensure the same inputs
always produce the same output, enabling safe retries.
-}
module Iidy.Aws.ClientReqToken (
    TokenInfo (..),
    TokenSource (..),
    DerivedTokenInfo (..),
    deriveTokenForStep,
    formatTokenSource,
    generateTokenFromMaybe,
) where

import Data.ByteArray (convert)
import Data.ByteArray.Encoding (Base (..), convertToBase)
import Data.ByteString (ByteString)
import Data.Text (Text)
import Data.Text qualified as T
import Data.Text.Encoding (decodeUtf8, encodeUtf8)
import Data.UUID qualified as UUID
import Data.UUID.V4 (nextRandom)

import Crypto.Hash (SHA256 (..), hashWith)

data DerivedTokenInfo = DerivedTokenInfo
    { dtiFrom :: !Text
    , dtiStep :: !Text
    }
    deriving stock (Show, Eq)

data TokenSource
    = UserProvided
    | AutoGenerated
    | Derived !DerivedTokenInfo
    deriving stock (Show, Eq)

data TokenInfo = TokenInfo
    { tiValue :: !Text
    , tiSource :: !TokenSource
    , tiOperationId :: !Text
    }
    deriving stock (Show, Eq)

{- | Derive a new token for a specific operation step.
Uses SHA256 hash of (primary_token + step) for deterministic derivation.
Format: "{primary_first_8_chars}-{hash_first_8_chars}"
-}
deriveTokenForStep :: TokenInfo -> Text -> TokenInfo
deriveTokenForStep primary step =
    let input = encodeUtf8 (tiValue primary <> step)
        digest = hashWith SHA256 input
        hashBytes = convert digest :: ByteString
        hashHex = T.toLower $ decodeUtf8 (convertToBase Base16 hashBytes)
        prefix = T.take 8 (tiValue primary)
        suffix = T.take 8 hashHex
        derivedValue = prefix <> "-" <> suffix
     in TokenInfo
            { tiValue = derivedValue
            , tiSource =
                Derived
                    DerivedTokenInfo
                        { dtiFrom = tiValue primary
                        , dtiStep = step
                        }
            , tiOperationId = tiOperationId primary
            }

-- | Generate a client request token (user-provided or auto-generated UUID)
generateTokenFromMaybe :: Maybe Text -> IO TokenInfo
generateTokenFromMaybe (Just t) =
    pure
        TokenInfo
            { tiValue = t
            , tiSource = UserProvided
            , tiOperationId = t
            }
generateTokenFromMaybe Nothing = do
    uuid <- nextRandom
    let val = T.pack (UUID.toString uuid)
    pure
        TokenInfo
            { tiValue = val
            , tiSource = AutoGenerated
            , tiOperationId = val
            }

-- | Format a token source for display
formatTokenSource :: TokenSource -> Text
formatTokenSource = \case
    UserProvided -> "user-provided"
    AutoGenerated -> "auto-generated"
    Derived dti -> "derived from " <> dtiFrom dti <> " at " <> dtiStep dti
